services:
  kleinbot:
    image: kleinbot:cookie
    container_name: kleinbot
    shm_size: 1g
    environment:
      - DISPLAY=:0
      #- KLEINBOT_NAME=kleinbot
      - LOGGING_ENABLE=TRUE
      - CHROMIUM_PROFILE=/mnt/data/cache
      - SHARED_ADS=/docker/klein/shared/ads
      #- KLEINBOT_COOKIE=/mnt/data/kleinanzeigen_cookies.json
      #- KLEINBOT_STORAGE=/mnt/data/kleinanzeigen_localstorage.json
    volumes:
      - /docker/klein/shared/ads:/mnt/data/ads:rw
      - /docker/klein/shared/ads/pics:/mnt/data/ads/pics:rw
      - /docker/klein/bot/data:/mnt/data:rw
      - /docker/klein/manager/data:/
    ports:
      - "6080:6080"   # Zugriff Ã¼ber Browser (NoVNC)
      - "5900:5900"   # optional Zugriff per VNC-Client
